### ISSUE TITLE
Cloud-init?

### ISSUE THREAD

**Issue by cornuwel** [SineQuaNonSoftware/puppet-proxmox#10]
Not sure we want to add this option given the current limitations, you tell me...

**Comment by cgoubert** [comment]
Needs extensive testing before, and I'm not sure I'm comfortable with embedding a forum patch in a shared module.
For context : 

ProxmoxVE for now doesn't pass vendor-data, and doesn't merge custom cloud-init userdata and networkdata with default cloud-init configs from the template. There is [a patch](https://forum.proxmox.com/threads/combining-custom-cloud-init-with-auto-generated.59008/post-323060) in proxmox forums, but we have not been able to make it work yet.
