### ISSUE TITLE
Move CI to CircleCI

### ISSUE THREAD

**Issue by cornuwel** [SineQuaNonSoftware/puppet-proxmox#17]
In an effort of consolidation, I'm trying to get it to work from CircleCI.
Every push is checked for syntax and linting.

Pushes to master with a tag that matches metadata.json will automatically push the module to the Puppet Forge.

**Comment by cornuwel** [comment]
https://github.com/SineQuaNonSoftware/puppet-proxmox/pull/16

**Comment by cgoubert** [comment]
Merged.

**Comment by cgoubert** [comment]
Maybe I shouldn't have. Deploy is borked.

**Comment by cgoubert** [comment]
As far as I can gather, that's the check you talked about regarding tag vs metadata for build ? Shouldn't it just "not deploy" in that case instead of the step breaking ?

**Comment by cgoubert** [comment]
Apparently it's just "the way the orb does it" and not a choice on our part.
That means we will end up ignoring every test result on master when we're not pushing a release tag.

**Comment by cornuwel** [comment]
Yeah, I think I can specify the step is allowed to fail (yellow ball instead of the green tick).
I didn't read the publish code in detail. I just wanted to have the basic syntax checks for every branch and PR.
I'll need to figure out how that exactly works to make it try and deploy only if the tag is there.

Creating a new issue to fix the deployment part.
